ganglia/urls.py
from django.conf.urls import patterns, url
from ganglia import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),	
	url(r'^host(?P<host_id>\d+)/$', views.host_info, name='host_info'),
	url(r'^host(?P<host_id>\d+)/res(?P<resource_id>\d+)/$', views.res_info, name='res_info'),
    url(r'^log/$', views.all_log, name='log_page'),
    url(r'^xml/(?P<host_name>\S+)/(?P<rrd_name>\w+)/(?P<time_slot>\d+)/$', views.get_text),
    url(r'^last_update/(?P<host_name>\S+)/$', views.last_update),
    url(r'^last_mtc_avg/(?P<rrd_name>\w+)/$', views.last_mtc_avg),
    url(r'^hour_mtc_avg/(?P<rrd_name>\w+)/$', views.hour_mtc_avg),
    url(r'^get_log/$', views.get_log),
    url(r'^alert_post/$', views.deal_log),
    url(r'^coreos-host/$', views.coreos_host, name='coreos-host'),
    url(r'^deploy/$', views.deploy_app, name='deploy-app')
)

monitor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^ganglia/', include('ganglia.urls',namespace="ganglia")),
    url(r'^admin/', include(admin.site.urls)),
)

ganglia/models.py
from django.db import models

# Create your models here.
class Host(models.Model):
	host_name = models.CharField(max_length=200)
	host_ip = models.CharField(max_length=200)
	def __unicode__(self):
		return self.host_name

class Resource(models.Model):
	host = models.ForeignKey(Host)
	res_hostname = models.CharField(max_length=200)
	res_name = models.CharField(max_length=200)
	res_type = models.CharField(max_length=200)
	def __unicode__(self):
		return self.res_name

class Metric(models.Model):
	resource = models.ForeignKey(Resource)
	metric_name = models.CharField(max_length=200)
	mtr_hostname = models.CharField(max_length=200)
	def __unicode__(self):
		return self.metric_name


class Log(models.Model):
	host = models.CharField(max_length=200)
	res_name = models.CharField(max_length=200)
	mtc_type = models.CharField(max_length=200)
	time = models.DateTimeField('date of log')
	log_info = models.CharField(max_length=2000)
	def __unicode__(self):
		return self.res_name + "_log"

	
	

ganglia/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from ganglia.models import Resource,Metric,Host,Log
import json
from ganglia.util import str_to_list,res_img,read_ganglia_conf,add_items,reason_func
import os 
import commands 
from sys import stdin,stdout,stderr
import time 
from django.utils import timezone


# Create your views here.
def index(request):
    #add content to database
    hname_list = read_ganglia_conf()
    add_items(hname_list)
    #get content from table
    host_list = Host.objects.all()
    resource_list = Resource.objects.all()
#    get_relate(resource_list)
    context = {'resource_list': resource_list,'host_list':host_list}
    return render(request,'ganglia/index.html',context)

def host_info(request,host_id):
    host = get_object_or_404(Host,pk=host_id)
    res_list = Resource.objects.filter(host=host);
    context = {'host':host,'res_list':res_list}    
    return render(request,'ganglia/host.html',context)

def res_info(request,host_id,resource_id):    
    res = get_object_or_404(Resource,pk=resource_id)
    mtc_list = Metric.objects.filter(resource=res)
    #get related res list 
    rel_namelist = reason_func(res.res_name)
    rel_list = []
    for rel_name in rel_namelist:
        """attention after filter you get a list"""
        rel_fil = Resource.objects.filter(res_name=rel_name.strip(),res_hostname=res.res_hostname)
        if not len(rel_fil)==0:
            rel_list.append(rel_fil[0])

    context = {'res':res,'mtc_list':mtc_list,'relate_list':rel_list,'host_id':host_id}
    return render(request,'ganglia/res.html',context);

'''
considering there is one and only one specified cluster
this function generated the according xml of the rrd
'''
def get_text(request, host_name, rrd_name, time_slot):
    base_url = "/var/lib/ganglia/rrds/my_cluster/"
    rrd_path = base_url + host_name + "/" + rrd_name + ".rrd"

    end = "now"    
    if time_slot == "1": 
        start = "end-300"
        step = "3"
    elif time_slot == "2":
        start = "end-1d"
        step = "240"
    elif time_slot == "3":
        start = "end-1w"
        step = "1200"
    elif time_slot == "4":
        start = "end-1m"
        step = "4000"
    # for index page get resource utilization 
    elif time_slot == "8":      
        start = "end-60"
        step = "15" 
    else:        
        start = "end-600"
        step = "10"
    command = "rrdtool xport --start %s --end %s DEF:ds=%s:sum:AVERAGE:step=%s XPORT:ds:legend" % (start,end,rrd_path,step)
    status,output = commands.getstatusoutput(command)
    return HttpResponse(output)


'''
get the last update time of the host metrics 
return UNIX timestamp and now time interval 
'''
def last_update(request,host_name):
    base_url = "/var/lib/ganglia/rrds/my_cluster/" + host_name + "/load_one.rrd";
    command = "rrdtool lastupdate %s" % base_url
    status,output = commands.getstatusoutput(command)
    '''
    output string format is: 
     sum

     timestamp:  value
    '''
    #get the time stamp
    start = output.rindex("\n") + 1
    end = output.index(":")
    update_time = int(output[start:end])

    now_ts = int(time.time())
    interval = now_ts - update_time
    return HttpResponse(interval)


#get avg of specified mtc of all hosts of last_update
#for overview 
def last_mtc_avg(request,rrd_name):
    base_url = "/var/lib/ganglia/rrds/my_cluster/__SummaryInfo__/" + rrd_name +".rrd"
    command = "rrdtool lastupdate %s" % base_url
    status,output = commands.getstatusoutput(command)
    
    #get value sum and host num 
    #output format is 
    # sum num
    #
    # 1428893532: 2.3 1
    start = output.index(":") + 2
    v_pair = output[start:]
    return HttpResponse(v_pair)



#all hosts's avg metric value during last hour
def hour_mtc_avg(request,rrd_name):
    base_url = "/var/lib/ganglia/rrds/my_cluster/__SummaryInfo__/" + rrd_name +".rrd"
    command = "rrdtool xport --start end-1h --end now --step 10 DEF:ds1=%s:sum:AVERAGE DEF:ds2=%s:num:AVERAGE XPORT:ds1:sum XPORT:ds2:num" % (base_url,base_url)
    status, output = commands.getstatusoutput(command)
    return HttpResponse(output)


#this func deal with alert post data, store it in to Log database
def deal_log(request):
    if request.POST:
        hostname = request.POST['host_name']
        resname = request.POST['res_name']
        mtcname = request.POST['mtc_name']
        log_info = request.POST['log_info']
        #save the log to Log table in db
        log = Log(host=hostname,res_name=resname,mtc_type=mtcname,time=timezone.now(),log_info=log_info)
        log.save()
        return HttpResponse("%s %s %s %s" % (hostname,mtcname,time,log_info));


#get the latest 8 log info
def get_log(request):
    lastest_log_list = Log.objects.order_by('-time')[:8]
    re_list = []
    for log in lastest_log_list:
        log_dict = {}
        log_dict['owner'] = "%s->%s->%s" % (log.host, log.res_name,log.mtc_type);
        log_dict['info'] = log.log_info
        log_dict['time'] = log.time
        re_list.append(log_dict)

    #False for not dict 
    return JsonResponse(re_list, safe=False) 



def all_log(request):
    log_list = Log.objects.all()
    context = {'log_list':log_list}
    return render(request,'ganglia/log.html',context)



############ for coreOS manager #####################

def coreos_host(request):
    return render(request,'ganglia/coreos_host.html')



def deploy_app(request):
    return render(request,'ganglia/deploy.html')
############ for coreOS manager #####################

ganglia/templates/ganglia/host.html
{% extends "ganglia/base.html" %}

{% block content %}
{% load staticfiles %}
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ganglia:index'%}">Monitor Admin Dashboard</a>                
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                   
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                    
                <!-- /.dropdown-tasks -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                    
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="sidebar">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">                        
                    <li>
                        <div align=center class="sm-container">
                        	<img src="{% static 'ganglia/images/pc.png' %}" height="150" width="150"></img>
                        	<h4>{{ host.host_name }}</h4>
                            <!-- <div class="demo-placeholder" id="graph-holder"></div> -->
                        </div>
                    </li>                                                
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Resources<i class="fa arrow"></i></a>
                        <ul class="nav nav-second-level">
                           {% if res_list %}
                           {% for res in res_list %}
                           <li>
                            <a href="{% url 'ganglia:res_info' host.id res.id %}">{{ res.res_name }}</a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li>
                         <a href="#">no res yet...</a>
                     </li>
                     {% endif%}                                
                 </ul>
                 <!-- /.nav-second-level -->
             </li>                                   
         </ul>
     </div>
     <!-- /.sidebar-collapse -->
 </div>
 <!-- /.navbar-static-side -->
</nav>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ host.host_name }} Overview</h1>
        </div>
    </div>
    <!-- /.row -->            
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-6">        
        	<div class="box box-primary">
                <div class="box-header" style="background:#eeeeee">
                  <i class="fa fa-bar-chart-o"></i>
                  <h3 class="box-title">cpu</h3>
                  <span style="padding-left:150px" id='time_cpu'>last hour</span>
                  <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Time
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a onclick="switch_time('cpu','1')">last hour</a>
                            </li>                                
                            <li><a onclick="switch_time('cpu','2')">last day</a>
                            </li>
                            <li><a onclick="switch_time('cpu','3')">last week</a>
                            </li>
                            <li><a onclick="switch_time('cpu','4')">last month</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="box-body">
              <div id="cpu-chart" style="height: 300px;">
                  <div class="mid-container">
                    <div class="demo-placeholder" id="cpu-chart"></div>
                  </div>
              </div>
          </div><!-- /.box-body-->
      </div><!-- /.box -->

      <div class="box box-primary">
        <div class="box-header" style="background:#eeeeee">
          <i class="fa fa-bar-chart-o"></i>
          <h3 class="box-title">mem</h3>
          <span style="padding-left:150px" id='time_mem'>last hour</span>          
          <div class="pull-right">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                    Time
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li><a onclick="switch_time('mem','1')">last hour</a>
                    </li>                                
                    <li><a onclick="switch_time('mem','2')">last day</a>
                    </li>
                    <li><a onclick="switch_time('mem','3')">last week</a>
                    </li>
                    <li><a onclick="switch_time('mem','4')">last month</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="box-body">
      <div id="mem-chart" style="height: 300px;">
          <div class="mid-container">
            <div class="demo-placeholder" id="mem-chart"></div>
        </div>
      </div>
  </div><!-- /.box-body-->
</div><!-- /.box -->            

</div>
<!-- /.col-lg-6 -->

<div class="col-lg-6">
    <div class="box box-primary">
        <div class="box-header" style="background:#eeeeee">
          <i class="fa fa-bar-chart-o"></i>
          <h3 class="box-title">disk</h3>
          <span style="padding-left:150px" id='time_disk'>last hour</span>
          <div class="pull-right">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                    Time
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li><a onclick="switch_time('disk','1')">last hour</a>
                    </li>                                
                    <li><a onclick="switch_time('disk','2')">last day</a>
                    </li>
                    <li><a onclick="switch_time('disk','3')">last week</a>
                    </li>
                    <li><a onclick="switch_time('disk','4')">last month</a>
                    </li>
            </div>
        </div>
    </div>
    <div class="box-body">
      <div id="disk-chart" style="height: 300px;">
          <div class="mid-container">
            <div class="demo-placeholder" id="disk-chart"></div>
        </div>
      </div>
  </div><!-- /.box-body-->
</div><!-- /.box -->

<div class="box box-primary">
    <div class="box-header" style="background:#eeeeee">
      <i class="fa fa-bar-chart-o"></i>
      <h3 class="box-title">network</h3>
      <span style="padding-left:150px" id='time_net'>last hour</span>
      <div class="pull-right">
        <div class="btn-group">
            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                Time
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
                <li><a onclick="switch_time('net','1')">last hour</a>
                </li>                                
                <li><a onclick="switch_time('net','2')">last day</a>
                </li>
                <li><a onclick="switch_time('net','3')">last week</a>
                </li>
                <li><a onclick="switch_time('net','4')">last month</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="box-body">
  <div id="net-chart" style="height: 300px;">
        <div class="mid-container">
            <div class="demo-placeholder" id="net-chart"></div>
        </div>
  </div>
</div><!-- /.box-body-->
</div><!-- /.box -->
</div>

<!-- /.col-lg-4 -->
</div>
<!-- /.row -->

</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->
{% load staticfiles%}    
<script src="{% static 'ganglia/dist/js/util.js' %}"></script>
<script src="{% static 'ganglia/dist/js/host_data.js' %}"></script>

<script type="text/javascript">     
var hostname = '{{ host.host_name }}';
</script>
{% endblock %}

ganglia/templates/ganglia/index.html
{% extends "ganglia/base.html" %}

{% block content %}
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ganglia:index'%}">Monitor Admin Dashboard</a>                
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                   
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                    
                <!-- /.dropdown-tasks -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>                    
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">                        
                    <li>
                        <div class="sm-container">
                            <div class="demo-placeholder" id="graph-holder"></div>
                        </div>
                    </li>
                        <!-- <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li> -->
                        <!-- <host list> -->
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Hosts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                {% if host_list %}
                                    {% for host in host_list %}
                                        <li>
                                            <a href="{% url 'ganglia:host_info' host.id %}">{{ host.host_name }}</a>
                                        </li>
                                    {% endfor %}
                                {% else %}
                                    <li>
                                        <a href="#">no host yet...</a>
                                    </li>
                                {% endif %}                                                              
                            </ul>
                        </li>
                        <!-- <host list> -->
                        <!-- <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Resources<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Cpu</a>
                                </li>
                                <li>
                                    <a href="#">Mem</a>
                                </li>
                                <li>
                                    <a href="#">Disk</a>
                                </li>
                                <li>
                                    <a href="#">Load</a>
                                </li>
                            </ul>
                        </li>                         -->
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i>coreOS<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">machine<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{% url 'ganglia:coreos-host'%}">host1</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'ganglia:coreos-host'%}">host2</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'ganglia:coreos-host'%}">host3</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="{% url 'ganglia:deploy-app'%}">deploy app</a>
                                </li>
                            </ul>
                        </li>                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Cluster Overview</h1>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-aqua">
                    <div class="inner">
                      <h3 id="cpu_util">0</h3>
                      <h4>Cluster CPU ultilization</h4>
                  </div>
                  <div class="icon">
                      <i class="ion ion-pie-graph"></i>
                  </div>
                  <a href="#" class="small-box-footer">cpu <!-- <i class="fa fa-arrow-circle-right"></i> --></a>
              </div>
          </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3 id="mem_util">0</h3>
                  <h4>Cluster Mem ultilization</h4>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">mem</a>
              </div>
            </div><!-- ./col -->   
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h3 id="disk_util">0</h3>
                  <h4>Cluster Disk ultilization</h4>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">disk</a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h3 id="load_one">0</h3>
                  <h4>Cluster Load One</h4>
                </div>
                <div class="icon">
                  <i class="ion ion-cube"></i>
                </div>
                <a href="#" class="small-box-footer">load_one</a>
              </div>
            </div><!-- ./col -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <span id="on_show_metric">cluster cpu last_hour </span>
                    <div class="pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                Metrics
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="#" onclick="show_metric('cpu')">cluster Cpu last_hour</a>
                                </li>
                                <li><a href="#" onclick="show_metric('mem')">cluster Mem last_hour</a>
                                </li>
                                <li><a href="#" onclick="show_metric('network')">cluster network last_hour</a>
                                </li>
                                <li><a href="#" onclick="show_metric('load')">cluster Load last_hour</a>
                                </li>                                                                
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div id="metric-graph">                    
                    <div class="lg-container" style="display:block">
                        <div class="demo-placeholder" id="area-chart"></div>
                    </div>                    	            
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->            
            <!-- /.panel -->                    
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> Alert Log
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="list-group" id="log_list">
                    </div>
                    <!-- /.list-group -->
                    <a href="{% url 'ganglia:log_page'%}" class="btn btn-default btn-block">View All Alerts</a>
                </div>
                <!-- /.panel-body -->
            </div>            
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->        
{% load staticfiles%}    
<script src="{% static 'ganglia/dist/js/util.js' %}"></script>
<script src="{% static 'ganglia/dist/js/index_data.js' %}"></script>
<script src="{% static 'ganglia/js/morris-data.js' %}"></script>

<script type="text/javascript">     

//judge a host down if it didn't update for 2 minutes
//num[0] for up host num[1] for down host
function get_host_num(){            
    var num = [];
    num[0] = 0;
    num[1] = 0;            
    var base_url = "/ganglia/last_update/";
    {% if host_list %}                
    {% for host in host_list %}                                    
    var req_url = base_url + '{{ host.host_name }}';
    var update_interval = get_update_host(req_url);
    if(update_interval < 120)
        num[0] += 1;
    else 
        num[1] += 1;
    {% endfor %}
    {% else %}
    num[0] = 0;
    num[1] = 0;                
    {% endif %}            
    return num;            
}                

</script>

{% endblock %}